# Generated by Django 5.0.6 on 2024-06-15 17:16

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="first name")),
                ("last_name", models.CharField(max_length=100, verbose_name="last name")),
                (
                    "display_name",
                    models.CharField(db_index=True, max_length=100, unique=True, verbose_name="display name"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/artist.jpg",
                        upload_to=apps.core.services.get_path_upload_image_artist,
                        validators=[apps.core.services.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                ("is_verify", models.BooleanField(default=False, verbose_name="is verify")),
            ],
            options={
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
