# Generated by Django 5.0.6 on 2024-07-22 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="artist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="artistverificationrequest",
            name="artist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="verification_requests", to="artists.artist"
            ),
        ),
        migrations.AddField(
            model_name="favoriteartist",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="favorite_artists", to="artists.artist"
            ),
        ),
        migrations.AddField(
            model_name="favoriteartist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_artists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="licenses", to="artists.artist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoriteartist",
            unique_together={("user", "artist")},
        ),
    ]
