# Generated by Django 5.0.6 on 2024-07-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
            },
        ),
    ]
