# Generated by Django 5.0.6 on 2024-06-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistVerificationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_processed", models.BooleanField(default=False, verbose_name="is processed")),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artist verification request",
                "verbose_name_plural": "Artist verification requests",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
