# Generated by Django 5.0.6 on 2024-07-09 20:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_artist_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="color",
            field=colorfield.fields.ColorField(default="#202020", image_field=None, max_length=25, samples=None),
        ),
    ]
