# Generated by Django 5.0.6 on 2024-07-16 22:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0005_favoriteartist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoriteartist",
            unique_together={("user", "artist")},
        ),
    ]
