# Generated by Django 5.0.6 on 2024-06-17 12:39

import apps.core.services
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0003_license"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="title")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/album.jpg",
                        upload_to=apps.core.services.get_path_upload_image_album,
                        validators=[apps.core.services.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                ("is_private", models.BooleanField(default=False, verbose_name="is_private")),
                (
                    "artist",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="artists.artist",
                        verbose_name="artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "album",
                "verbose_name_plural": "albums",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
