# Generated by Django 5.0.6 on 2024-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_alter_album_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="description"),
        ),
    ]
