# Generated by Django 5.0.6 on 2024-07-10 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0005_album_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="release_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name="release date"
            ),
        ),
    ]
