# Generated by Django 5.0.6 on 2024-07-21 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0008_alter_favoritealbum_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateField(
                blank=True, default=datetime.date(2024, 7, 21), null=True, verbose_name="release date"
            ),
        ),
    ]
