# Generated by Django 5.0.6 on 2024-06-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"verbose_name": "Feature", "verbose_name_plural": "Features"},
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"verbose_name": "Subscription plan", "verbose_name_plural": "Subscription plans"},
        ),
    ]
