# Generated by Django 5.0.6 on 2024-06-17 12:39

import apps.core.services
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("albums", "0001_initial"),
        ("artists", "0003_license"),
        ("other", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="title")),
                ("duration", models.DurationField(blank=True, null=True, verbose_name="duration")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/track.jpg",
                        upload_to=apps.core.services.get_path_upload_image_track,
                        validators=[apps.core.services.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default="",
                        upload_to=apps.core.services.get_path_upload_track,
                        validators=[apps.core.services.validate_track_size],
                        verbose_name="file track",
                    ),
                ),
                ("plays_count", models.PositiveBigIntegerField(default=0, verbose_name="plays count")),
                ("downloads_count", models.PositiveBigIntegerField(default=0, verbose_name="downloads count")),
                ("likes_count", models.PositiveBigIntegerField(default=0, verbose_name="likes count")),
                ("is_private", models.BooleanField(default=False, verbose_name="is private")),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime(2024, 6, 17, 12, 39, 16, 924741, tzinfo=datetime.timezone.utc),
                        null=True,
                        verbose_name="release date",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="albums.album",
                        verbose_name="album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="artists.artist",
                        verbose_name="artist",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="other.genre",
                        verbose_name="genre",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="artists.license",
                        verbose_name="license",
                    ),
                ),
                (
                    "user_of_likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_tracks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user of likes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
