# Generated by Django 5.0.6 on 2024-06-19 16:40

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="file",
            field=models.FileField(
                upload_to=apps.core.services.get_path_upload_track,
                validators=[apps.core.services.validate_track_size],
                verbose_name="file track",
            ),
        ),
    ]
