# Generated by Django 5.0.6 on 2024-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
            },
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
