# Generated by Django 5.0.6 on 2024-07-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_alter_track_options_alter_track_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["-updated_at"], "verbose_name": "Track", "verbose_name_plural": "Tracks"},
        ),
    ]
