# Generated by Django 5.0.6 on 2024-06-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_feature_options_alter_subscriptionplan_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="subscriptions.subscriptionplan",
            ),
        ),
    ]
