# Generated by Django 5.0.6 on 2024-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_profile",
            field=models.CharField(
                choices=[("user", "User"), ("artist", "Artist")],
                default="artist",
                max_length=20,
                verbose_name="type profile",
            ),
        ),
    ]
