# Generated by Django 5.0.6 on 2024-06-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Artist",
                "verbose_name_plural": "Artists",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
