# Generated by Django 5.0.6 on 2024-07-22 00:45

import apps.core.services
import autoslug.fields
import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoritePlaylist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Favorite playlist",
                "verbose_name_plural": "Favorite playlists",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, max_length=500, verbose_name="description")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/playlist.jpg",
                        upload_to=apps.core.services.get_path_upload_image_playlist,
                        validators=[apps.core.services.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#202020", image_field=None, max_length=25, samples=None),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="release date"),
                ),
                ("is_private", models.BooleanField(default=False, verbose_name="is_private")),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
