# Generated by Django 5.0.6 on 2024-06-18 20:42

import apps.core.services
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio", "0001_initial"),
        ("other", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/track.jpg",
                        upload_to=apps.core.services.get_path_upload_image_playlist,
                        validators=[apps.core.services.validate_image_size],
                        verbose_name="image",
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True, verbose_name="release date")),
                ("is_private", models.BooleanField(default=False, verbose_name="is_private")),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playlists",
                        to="other.genre",
                    ),
                ),
                ("tracks", models.ManyToManyField(related_name="playlists", to="audio.track")),
            ],
            options={
                "verbose_name": "playlist",
                "verbose_name_plural": "playlists",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
