# Generated by Django 5.0.6 on 2024-07-06 16:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_alter_playlist_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True, default="", image_field="image", max_length=25, samples=None
            ),
        ),
    ]
