# Generated by Django 5.0.6 on 2024-07-16 22:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0006_alter_playlist_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoriteplaylist",
            unique_together={("user", "playlist")},
        ),
    ]
