# Generated by Django 5.0.6 on 2024-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0007_alter_favoriteplaylist_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="title"),
        ),
    ]
