# Generated by Django 5.0.6 on 2024-07-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0002_alter_genre_color"),
        ("playlists", "0010_alter_playlist_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlists",
                to="other.genre",
            ),
        ),
    ]
