# Generated by Django 5.0.6 on 2024-06-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_trackplayed_delete_trackplays"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="similarity",
            options={"verbose_name": "Similarity", "verbose_name_plural": "Similarities"},
        ),
        migrations.AlterModelOptions(
            name="trackplayed",
            options={"verbose_name": "Track Play", "verbose_name_plural": "Track Plays"},
        ),
    ]
